package com.example

object AppStrings {
    private val strings = mapOf(
        "en" to mapOf(
            "nav_home" to "Home",
            "market_rates" to "Live Mandi Rates",
            "nav_market" to "Market",
            "nav_scan" to "Scan",
            "nav_chat" to "Chat",
            "nav_profile" to "Profile",
            "detecting" to "Detecting...",
            "auto_detect" to "Auto-Detect Location",
            "powered_by" to "Direct Agmarknet Govt API Integration",
            "search_placeholder" to "Enter crop (e.g. Tomato, Wheat...)",
            "search_btn" to "Search",
            "popular_crops" to "Popular Crops",
            "fetching_live" to "Fetching live govt API data for",
            "no_live_data" to "No live market data found for",
            "try_different" to "Try a different crop or location.",
            "mandi" to "Mandi",
            "modal_price" to "Modal Price (INR/Quintal)",
            "variety" to "Variety:",
            "min" to "Min:",
            "max" to "Max:",
            "track_price" to "🔔 Track Price",
            "tracking_active" to "✅ Tracking",
            "edit_location" to "Edit Location",
            "enter_state" to "State (e.g. Punjab)",
            "enter_mandi" to "Mandi (e.g. Khanna)",
            "save" to "Save",
            "cancel" to "Cancel",
            "scanner_title" to "AI Crop Doctor",
            "take_photo" to "Take Photo",
            "upload_gallery" to "Upload Gallery",
            "analyzing" to "Analyzing image...",
            "chat_placeholder" to "Ask NuKropAI...",
            "chat_title" to "NuKropAI Assistant",
            "weather_alerts" to "Market & Weather Alerts Active",
            "nav_autopilot" to "Autopilot",
            "nav_finance" to "Finance",
            "nav_rental" to "Equipment",
            "nav_khata" to "Farm Khata",
            "good_farmer" to "Good %s, Farmer!",
            "quick_actions" to "Quick Actions",
            "scan_crop" to "Scan Crop",
            "ai_disease" to "AI Disease & Pest Detect",
            "scan_soil" to "Scan Soil",
            "ai_soil" to "AI Soil Health Analysis",
            "market_rates_action" to "Market Rates",
            "live_mandi_prices" to "Live Mandi Prices",
            "ai_advisor" to "AI Advisor",
            "ask_question" to "Ask Any Farm Question",
            "loan_subsidy" to "Loan & Subsidy",
            "govt_schemes" to "Govt Schemes Matcher",
            "field_navigator" to "Field Navigator",
            "gps_route" to "GPS Route & Coverage",
            "my_tracked" to "My Tracked Prices",
            "pest_radar" to "Hyperlocal Pest Prediction AI",
            "high_risk" to "HIGH RISK",
            "report_outbreak" to "Report Outbreak in My Field",
            "outbreak_logged" to "Outbreak logged. Neighboring farmers alerted!",
            "ai_tasks" to "AI Task Schedules",
            "farm_tips" to "Today's Farm Tips",
            "subsidy_title" to "Government Schemes AI",
            "ai_matcher" to "AI Scheme Matcher",
            "find_subsidies" to "FIND MY SUBSIDIES",
            "scanning_gov" to "Scanning Gov Databases...",
            "outbreak_alerts_title" to "Regional Outbreak Alerts",
            "outbreak_epicenter" to "EPICENTER OUTBREAK",
            "outbreak_early_warning" to "EARLY WARNING ALERT",
            "no_active_alerts" to "No active epidemic alerts in your state",
            "grid_all_clear" to "National Outbreak Grid: Scan density normal (< 100 scans in 7 days).",
            "view_market_impact" to "View Market Price Impact",
            "scan_density_trigger" to "Density: %d scans detected (>%d threshold)",
            "market_impact_title" to "Outbreak Market Price Impact",
            "predicted_peak_price" to "Predicted Peak Price",
            "confidence_score" to "Confidence Score",
            "risk_level" to "Risk Level",
            "farmer_advisory" to "Farmer Action Advisory",
            "affected_mandis" to "Affected APMC Mandis",
            "privacy_badge_title" to "National Outbreak Early Warning Grid",
            "privacy_badge_desc" to "Anonymous scan telemetry safely contributed to protect neighboring farmers. No personal identity shared."
        ),
        "hi" to mapOf(
            "nav_home" to "होम",
            "market_rates" to "लाइव मंडी भाव",
            "nav_market" to "बाजार",
            "nav_scan" to "स्कैन",
            "nav_chat" to "चैट",
            "nav_profile" to "प्रोफ़ाइल",
            "detecting" to "पता लगा रहा है...",
            "auto_detect" to "स्थान स्वतः खोजें",
            "powered_by" to "प्रत्यक्ष एगमार्कनेट सरकारी एपीआई एकीकरण",
            "search_placeholder" to "फसल दर्ज करें (जैसे टमाटर, गेहूं...)",
            "search_btn" to "खोजें",
            "popular_crops" to "लोकप्रिय फसलें",
            "fetching_live" to "सरकारी एपीआई डेटा प्राप्त कर रहा है...",
            "no_live_data" to "इसके लिए कोई लाइव बाजार डेटा नहीं मिला:",
            "try_different" to "कोई अन्य फसल या स्थान आज़माएं।",
            "mandi" to "मंडी",
            "modal_price" to "औसत मूल्य (INR/क्विंटल)",
            "variety" to "किस्म:",
            "min" to "न्यूनतम:",
            "max" to "अधिकतम:",
            "track_price" to "🔔 मूल्य ट्रैक करें",
            "tracking_active" to "✅ ट्रैकिंग सक्रिय",
            "edit_location" to "स्थान बदलें",
            "enter_state" to "राज्य (जैसे पंजाब)",
            "enter_mandi" to "मंडी (जैसे खन्ना)",
            "save" to "सहेजें",
            "cancel" to "रद्द करें",
            "scanner_title" to "एआई फसल डॉक्टर",
            "take_photo" to "फोटो लें",
            "upload_gallery" to "गैलरी से अपलोड करें",
            "analyzing" to "छवि का विश्लेषण हो रहा है...",
            "chat_placeholder" to "NuKropAI से पूछें...",
            "chat_title" to "NuKropAI सहायक",
            "weather_alerts" to "बाजार और मौसम अलर्ट सक्रिय",
            "nav_autopilot" to "ऑटोपायलट",
            "nav_finance" to "वित्त",
            "good_farmer" to "शुभ %s, किसान!",
            "quick_actions" to "त्वरित कार्य",
            "scan_crop" to "फसल स्कैन",
            "ai_disease" to "एआई रोग एवं कीट पहचान",
            "scan_soil" to "मिट्टी स्कैन",
            "ai_soil" to "एआई मिट्टी स्वास्थ्य विश्लेषण",
            "market_rates_action" to "बाजार भाव",
            "live_mandi_prices" to "लाइव मंडी भाव",
            "ai_advisor" to "एआई सलाहकार",
            "ask_question" to "कोई भी कृषि प्रश्न पूछें",
            "loan_subsidy" to "ऋण एवं सब्सिडी",
            "govt_schemes" to "सरकारी योजना मैचर",
            "field_navigator" to "खेत नेविगेटर",
            "gps_route" to "GPS मार्ग एवं कवरेज",
            "my_tracked" to "मेरी ट्रैक की गई कीमतें",
            "pest_radar" to "हाइपरलोकल कीट पूर्वानुमान एआई",
            "high_risk" to "उच्च जोखिम",
            "report_outbreak" to "मेरे खेत में प्रकोप की रिपोर्ट करें",
            "outbreak_logged" to "प्रकोप दर्ज किया गया। पड़ोसी किसानों को सूचित किया!",
            "ai_tasks" to "एआई कार्य अनुसूची",
            "farm_tips" to "आज की कृषि सुझाव",
            "subsidy_title" to "सरकारी योजनाएं एआई",
            "ai_matcher" to "एआई योजना मैचर",
            "find_subsidies" to "मेरी सब्सिडी खोजें",
            "scanning_gov" to "सरकारी डेटाबेस स्कैन हो रहा है...",
            "outbreak_alerts_title" to "क्षेत्रीय प्रकोप अलर्ट",
            "outbreak_epicenter" to "केंद्रबिंदू प्रकोप",
            "outbreak_early_warning" to "प्रारंभिक चेतावनी अलर्ट",
            "no_active_alerts" to "आपके राज्य में कोई सक्रिय महामारी अलर्ट नहीं है",
            "grid_all_clear" to "राष्ट्रीय प्रकोप ग्रिड: स्कैन घनता सामान्य (7 दिनों में < 100 स्कैन)।",
            "view_market_impact" to "बाजार मूल्य प्रभाव देखें",
            "scan_density_trigger" to "घनता: %d स्कैन मिले (>%d सीमा)",
            "market_impact_title" to "प्रकोप बाजार मूल्य प्रभाव",
            "predicted_peak_price" to "अनुमानित उच्चतम मूल्य",
            "confidence_score" to "विश्वास स्कोर",
            "risk_level" to "जोखिम स्तर",
            "farmer_advisory" to "किसान कार्य सलाह",
            "affected_mandis" to "प्रभावित एपीएमसी मंडियां",
            "privacy_badge_title" to "राष्ट्रीय प्रकोप प्रारंभिक चेतावनी ग्रिड",
            "privacy_badge_desc" to "पड़ोसी किसानों की सुरक्षा के लिए अज्ञात स्कैन टेलीमेट्री सुरक्षित रूप से साझा की गई। कोई व्यक्तिगत पहचान साझा नहीं की गई।"
        ),
        "te" to mapOf(
            "nav_home" to "హోమ్",
            "market_rates" to "ప్రత్యక్ష మార్కెట్ ధరలు",
            "nav_market" to "మార్కెట్",
            "nav_scan" to "స్కాన్",
            "nav_chat" to "చాట్",
            "nav_profile" to "ప్రొఫైల్",
            "detecting" to "కనుగొంటోంది...",
            "auto_detect" to "ఆటో-డిటెక్ట్ లొకేషన్",
            "powered_by" to "డైరెక్ట్ అగ్మార్కెట్ ప్రభుత్వ API ఇంటిగ్రేషన్",
            "search_placeholder" to "పంట పేరు నమోదు చేయండి (ఉదా. టమోటా, గోధుమ...)",
            "search_btn" to "వెతకండి",
            "popular_crops" to "ప్రముఖ పంటలు",
            "fetching_live" to "ప్రభుత్వ API డేటాను పొందుతోంది...",
            "no_live_data" to "దీనికి ప్రత్యక్ష మార్కెట్ డేటా కనుగొనబడలేదు:",
            "try_different" to "వేరే పంట లేదా స్థానాన్ని ప్రయత్నించండి.",
            "mandi" to "మండీ",
            "modal_price" to "సగటు ధర (INR/క్వింటాల్)",
            "variety" to "రకం:",
            "min" to "కనిష్ట:",
            "max" to "గరిష్ట:",
            "track_price" to "🔔 ధరను ట్రాక్ చేయండి",
            "tracking_active" to "✅ ట్రాకింగ్ అవుతోంది",
            "edit_location" to "స్థానాన్ని సవరించండి",
            "enter_state" to "రాష్ట్రం (ఉదా. పంజాబ్)",
            "enter_mandi" to "మండీ (ఉదా. ఖన్నా)",
            "save" to "సేవ్ చేయి",
            "cancel" to "రద్దు చేయి",
            "scanner_title" to "AI పంట డాక్టర్",
            "take_photo" to "ఫోటో తీయండి",
            "upload_gallery" to "గ్యాలరీ నుండి అప్‌లోడ్ చేయండి",
            "analyzing" to "చిత్రాన్ని విశ్లేషిస్తోంది...",
            "chat_placeholder" to "NuKropAI ని అడగండి...",
            "chat_title" to "NuKropAI సహాయకుడు",
            "weather_alerts" to "మార్కెట్ & వాతావరణ హెచ్చరికలు యాక్టివ్‌గా ఉన్నాయి",
            "nav_autopilot" to "ఆటోపైలట్",
            "nav_finance" to "ఫైనాన్స్",
            "subsidy_title" to "ప్రభుత్వ పథకాలు AI",
            "ai_matcher" to "AI స్కీమ్ మ్యాచర్",
            "find_subsidies" to "నా సబ్సిడీలను కనుగొనండి",
            "scanning_gov" to "ప్రభుత్వ డేటాబేస్లను స్కాన్ చేస్తోంది...",
            "outbreak_alerts_title" to "ప్రాంతీయ వ్యాప్తి హెచ్చరికలు",
            "outbreak_epicenter" to "కేంద్రబిందువు వ్యాప్తి",
            "outbreak_early_warning" to "ముందస్తు హెచ్చరిక అలర్ట్",
            "no_active_alerts" to "మీ రాష్ట్రంలో క్రియాశీల వ్యాప్తి హెచ్చరికలు లేవు",
            "grid_all_clear" to "జాతీయ వ్యాప్తి గ్రిడ్: సాంద్రత సాధారణం (7 రోజుల్లో < 100 స్కాన్లు).",
            "view_market_impact" to "మార్కెట్ ధర ప్రభావాన్ని చూడండి",
            "scan_density_trigger" to "సాంద్రత: %d స్కాన్లు గుర్తించబడ్డాయి (>%d పరిమితి)",
            "market_impact_title" to "వ్యాప్తి మార్కెట్ ధర ప్రభావం",
            "predicted_peak_price" to "అంచనా వేసిన గరిష్ట ధర",
            "confidence_score" to "విశ్వాస స్కోరు",
            "risk_level" to "ప్రమాద స్థాయి",
            "farmer_advisory" to "రైతు కార్యాచరణ సలహా",
            "affected_mandis" to "ప్రభావిత APMC మండీలు",
            "privacy_badge_title" to "జాతీయ వ్యాప్తి ముందస్తు హెచ్చరిక గ్రిడ్",
            "privacy_badge_desc" to "పొరుగు రైతులను రక్షించడానికి అనామక స్కాన్ టెలిమెట్రీ అందించబడింది. వ్యక్తిగత సమాచారం భాగస్వామ్యం చేయబడదు."
        ),
        "ta" to mapOf(
            "nav_home" to "முகப்பு",
            "market_rates" to "நேரடி மண்டி விலைகள்",
            "nav_market" to "சந்தை",
            "nav_scan" to "ஸ்கேன்",
            "nav_chat" to "அரட்டை",
            "nav_profile" to "சுயவிவரம்",
            "detecting" to "கண்டறியப்படுகிறது...",
            "auto_detect" to "தானாக கண்டறியும் இடம்",
            "powered_by" to "நேரடி அக்மார்க்நெட் அரசு ஏபிஐ ஒருங்கிணைப்பு",
            "search_placeholder" to "பயிரை உள்ளிடவும் (எ.கா. தக்காளி, கோதுமை...)",
            "search_btn" to "தேடு",
            "popular_crops" to "பிரபலமான பயிர்கள்",
            "fetching_live" to "நேரடி அரசு ஏபிஐ தரவு பெறப்படுகிறது...",
            "no_live_data" to "இதற்கான நேரடி சந்தை தரவு எதுவும் கிடைக்கவில்லை:",
            "try_different" to "வேறு பயிர் அல்லது இடத்தை முயற்சிக்கவும்.",
            "mandi" to "மண்டி",
            "modal_price" to "சராசரி விலை (INR/குவிண்டால்)",
            "variety" to "வகை:",
            "min" to "குறைந்தபட்ச:",
            "max" to "அதிகபட்ச:",
            "track_price" to "🔔 விலையை கண்காணிக்கவும்",
            "tracking_active" to "✅ கண்காணிப்பில் உள்ளது",
            "edit_location" to "இடத்தைத் திருத்தவும்",
            "enter_state" to "மாநிலம் (எ.கா. பஞ்சாப்)",
            "enter_mandi" to "மண்டி (எ.கா. கண்ணா)",
            "save" to "சேமி",
            "cancel" to "ரத்துசெய்",
            "scanner_title" to "AI பயிர் மருத்துவர்",
            "take_photo" to "புகைப்படம் எடு",
            "upload_gallery" to "கேலரியில் இருந்து பதிவேற்றவும்",
            "analyzing" to "படம் பகுப்பாய்வு செய்யப்படுகிறது...",
            "chat_placeholder" to "NuKropAI இடம் கேளுங்கள்...",
            "chat_title" to "NuKropAI உதவியாளர்",
            "weather_alerts" to "சந்தை மற்றும் வானிலை எச்சரிக்கைகள் செயலில் உள்ளன",
            "nav_autopilot" to "ஆட்டோபைலட்",
            "nav_finance" to "நிதி",
            "subsidy_title" to "அரசு திட்டங்கள் AI",
            "ai_matcher" to "AI திட்ட மேட்சர்",
            "find_subsidies" to "எனது மானியங்களைக் கண்டறியுங்கள்",
            "scanning_gov" to "அரசு தரவுத்தளங்களை ஸ்கேன் செய்கிறது...",
            "outbreak_alerts_title" to "பிராந்திய நோய் வெடிப்பு எச்சரிக்கைகள்",
            "outbreak_epicenter" to "மையப்பகுதி நோய் வெடிப்பு",
            "outbreak_early_warning" to "முன்கூட்டியே எச்சரிக்கை",
            "no_active_alerts" to "உங்கள் மாநிலத்தில் செயலில் உள்ள நோய் வெடிப்பு எச்சரிக்கைகள் இல்லை",
            "grid_all_clear" to "தேசிய நோய் வெடிப்பு கட்டமைப்பு: அடர்த்தி இயல்பானது (7 நாட்களில் < 100 ஸ்கேன்கள்).",
            "view_market_impact" to "சந்தை விலை தாக்கத்தைப் பார்க்கவும்",
            "scan_density_trigger" to "அடர்த்தி: %d ஸ்கேன்கள் கண்டறியப்பட்டன (>%d வரம்பு)",
            "market_impact_title" to "நோய் வெடிப்பு சந்தை விலை தாக்கம்",
            "predicted_peak_price" to "கணிக்கப்பட்ட உச்ச விலை",
            "confidence_score" to "நம்பகத்தன்மை மதிப்பீடு",
            "risk_level" to "ஆபத்து நிலை",
            "farmer_advisory" to "விவசாயி செயல் ஆலோசனை",
            "affected_mandis" to "பாதிக்கப்பட்ட ஏபிஎம்சி மண்டிகள்",
            "privacy_badge_title" to "தேசிய நோய் வெடிப்பு முன்கூட்டிய எச்சரிக்கை கட்டமைப்பு",
            "privacy_badge_desc" to "அண்டை விவசாயிகளைப் பாதுகாக்க அநாமதேய ஸ்கேன் டெலிமெட்ரி பாதுகாப்பாக வழங்கப்பட்டது."
        ),
        "mr" to mapOf(
            "nav_home" to "होम",
            "market_rates" to "थेट बाजार भाव",
            "nav_market" to "बाजार",
            "nav_scan" to "स्कॅन",
            "nav_chat" to "चॅट",
            "nav_profile" to "प्रोफाइल",
            "detecting" to "शोधत आहे...",
            "auto_detect" to "स्थान स्वयंचलित शोधा",
            "powered_by" to "थेट एगमार्कनेट सरकारी एपीआय एकत्रीकरण",
            "search_placeholder" to "पीक प्रविष्ट करा (उदा. टोमॅटो, गहू...)",
            "search_btn" to "शोधा",
            "popular_crops" to "लोकप्रिय पिके",
            "fetching_live" to "थेट सरकारी एपीआय डेटा मिळवत आहे...",
            "no_live_data" to "यासाठी थेट बाजार डेटा आढळला नाही:",
            "try_different" to "वेगळे पीक किंवा स्थान वापरून पहा.",
            "mandi" to "मंडी",
            "modal_price" to "सरासरी किंमत (INR/क्विंटल)",
            "variety" to "जात:",
            "min" to "किमान:",
            "max" to "कमाल:",
            "track_price" to "🔔 किंमत ट्रॅक करा",
            "tracking_active" to "✅ ट्रॅकिंग सक्रिय",
            "edit_location" to "स्थान बदला",
            "enter_state" to "राज्य (उदा. पंजाब)",
            "enter_mandi" to "मंडी (उदा. खन्ना)",
            "save" to "जतन करा",
            "cancel" to "रद्द करा",
            "scanner_title" to "एआई पीक डॉक्टर",
            "take_photo" to "फोटो काढा",
            "upload_gallery" to "गॅलरीमधून अपलोड करा",
            "analyzing" to "प्रतिमेचे विश्लेषण करत आहे...",
            "chat_placeholder" to "NuKropAI ला विचारा...",
            "chat_title" to "NuKropAI सहाय्यक",
            "weather_alerts" to "बाजार आणि हवामान सूचना सक्रिय",
            "nav_autopilot" to "ऑटोपायलट",
            "nav_finance" to "वित्त",
            "subsidy_title" to "सरकारी योजना AI",
            "ai_matcher" to "AI योजना मॅचर",
            "find_subsidies" to "माझे अनुदान शोधा",
            "scanning_gov" to "सरकारी डेटाबेस स्कॅन होत आहे...",
            "outbreak_alerts_title" to "प्रादेशिक उद्रेक सूचना",
            "outbreak_epicenter" to "केंद्रबिंदू उद्रेक",
            "outbreak_early_warning" to "पूर्वसूचना अलर्ट",
            "no_active_alerts" to "तुमच्या राज्यात कोणतीही सक्रिय उद्रेक सूचना नाही",
            "grid_all_clear" to "राष्ट्रीय उद्रेक ग्रिड: स्कॅन घनता सामान्य (7 दिवसांत < 100 स्कॅन).",
            "view_market_impact" to "बाजारभाव प्रभाव पहा",
            "scan_density_trigger" to "घनता: %d स्कॅन आढळले (>%d मर्यादा)",
            "market_impact_title" to "उद्रेक बाजारभाव प्रभाव",
            "predicted_peak_price" to "अंदाजित कमाल भाव",
            "confidence_score" to "विश्वासार्हता धावसंख्या",
            "risk_level" to "धोका पातळी",
            "farmer_advisory" to "शेतकरी कृती सल्ला",
            "affected_mandis" to "प्रभावित एपीएमसी बाजार",
            "privacy_badge_title" to "राष्ट्रीय उद्रेक पूर्वसूचना ग्रिड",
            "privacy_badge_desc" to "शेजारील शेतकऱ्यांच्या संरक्षणासाठी निनावी स्कॅन टेलिमेट्री सुरक्षितपणे दिली. कोणताही वैयक्तिक डेटा सामायिक केलेला नाही."
        )
    )

    fun get(key: String, lang: String): String {
        return strings[lang]?.get(key) ?: strings["en"]?.get(key) ?: key
    }
}
