package com.example

object AppStrings {
    private val strings = mapOf(
        "en" to mapOf(
            "nav_home" to "Home",
            "market_rates" to "Live Mandi Rates",
            "nav_market" to "Market",
            "nav_scan" to "Scan",
            "nav_chat" to "Chat",
            "nav_profile" to "Profile",
            "detecting" to "Detecting...",
            "auto_detect" to "Auto-Detect Location",
            "powered_by" to "Direct Agmarknet Govt API Integration",
            "search_placeholder" to "Enter crop (e.g. Tomato, Wheat...)",
            "search_btn" to "Search",
            "popular_crops" to "Popular Crops",
            "fetching_live" to "Fetching live govt API data for",
            "no_live_data" to "No live market data found for",
            "try_different" to "Try a different crop or location.",
            "mandi" to "Mandi",
            "modal_price" to "Modal Price (INR/Quintal)",
            "variety" to "Variety:",
            "min" to "Min:",
            "max" to "Max:",
            "track_price" to "🔔 Track Price",
            "tracking_active" to "✅ Tracking",
            "edit_location" to "Edit Location",
            "enter_state" to "State (e.g. Punjab)",
            "enter_mandi" to "Mandi (e.g. Khanna)",
            "save" to "Save",
            "cancel" to "Cancel",
            "scanner_title" to "AI Crop Doctor",
            "take_photo" to "Take Photo",
            "upload_gallery" to "Upload Gallery",
            "analyzing" to "Analyzing image...",
            "chat_placeholder" to "Ask NuKropAI...",
            "chat_title" to "NuKropAI Assistant",
            "weather_alerts" to "Market & Weather Alerts Active",
            "nav_autopilot" to "Autopilot",
            "nav_finance" to "Finance",
            "nav_rental" to "Equipment",
            "nav_khata" to "Farm Khata",
            "good_farmer" to "Good %s, Farmer!",
            "quick_actions" to "Quick Actions",
            "scan_crop" to "Scan Crop",
            "ai_disease" to "AI Disease & Pest Detect",
            "scan_soil" to "Scan Soil",
            "ai_soil" to "AI Soil Health Analysis",
            "market_rates_action" to "Market Rates",
            "live_mandi_prices" to "Live Mandi Prices",
            "ai_advisor" to "AI Advisor",
            "ask_question" to "Ask Any Farm Question",
            "loan_subsidy" to "Loan & Subsidy",
            "govt_schemes" to "Govt Schemes Matcher",
            "field_navigator" to "Field Navigator",
            "gps_route" to "GPS Route & Coverage",
            "my_tracked" to "My Tracked Prices",
            "pest_radar" to "Hyperlocal Pest Prediction AI",
            "high_risk" to "HIGH RISK",
            "report_outbreak" to "Report Outbreak in My Field",
            "outbreak_logged" to "Outbreak logged. Neighboring farmers alerted!",
            "ai_tasks" to "AI Task Schedules",
            "farm_tips" to "Today's Farm Tips",
            "subsidy_title" to "Government Schemes AI",
            "ai_matcher" to "AI Scheme Matcher",
            "find_subsidies" to "FIND MY SUBSIDIES",
            "scanning_gov" to "Scanning Gov Databases...",
            "outbreak_alerts_title" to "Regional Outbreak Alerts",
            "outbreak_epicenter" to "EPICENTER OUTBREAK",
            "outbreak_early_warning" to "EARLY WARNING ALERT",
            "no_active_alerts" to "No active epidemic alerts in your state",
            "grid_all_clear" to "National Outbreak Grid: Scan density normal (< 100 scans in 7 days).",
            "view_market_impact" to "View Market Price Impact",
            "scan_density_trigger" to "Density: %d scans detected (>%d threshold)",
            "market_impact_title" to "Outbreak Market Price Impact",
            "predicted_peak_price" to "Predicted Peak Price",
            "confidence_score" to "Confidence Score",
            "risk_level" to "Risk Level",
            "farmer_advisory" to "Farmer Action Advisory",
            "affected_mandis" to "Affected APMC Mandis",
            "privacy_badge_title" to "National Outbreak Early Warning Grid",
            "privacy_badge_desc" to "Anonymous scan telemetry safely contributed to protect neighboring farmers. No personal identity shared."
        ),
        "hi" to mapOf(
            "nav_home" to "होम",
            "market_rates" to "लाइव मंडी भाव",
            "nav_market" to "बाजार",
            "nav_scan" to "स्कैन",
            "nav_chat" to "चैट",
            "nav_profile" to "प्रोफ़ाइल",
            "detecting" to "पता लगा रहा है...",
            "auto_detect" to "स्थान स्वतः खोजें",
            "powered_by" to "प्रत्यक्ष एगमार्कनेट सरकारी एपीआई एकीकरण",
            "search_placeholder" to "फसल दर्ज करें (जैसे टमाटर, गेहूं...)",
            "search_btn" to "खोजें",
            "popular_crops" to "लोकप्रिय फसलें",
            "fetching_live" to "सरकारी एपीआई डेटा प्राप्त कर रहा है...",
            "no_live_data" to "इसके लिए कोई लाइव बाजार डेटा नहीं मिला:",
            "try_different" to "कोई अन्य फसल या स्थान आज़माएं।",
            "mandi" to "मंडी",
            "modal_price" to "औसत मूल्य (INR/क्विंटल)",
            "variety" to "किस्म:",
            "min" to "न्यूनतम:",
            "max" to "अधिकतम:",
            "track_price" to "🔔 मूल्य ट्रैक करें",
            "tracking_active" to "✅ ट्रैकिंग सक्रिय",
            "edit_location" to "स्थान बदलें",
            "enter_state" to "राज्य (जैसे पंजाब)",
            "enter_mandi" to "मंडी (जैसे खन्ना)",
            "save" to "सहेजें",
            "cancel" to "रद्द करें",
            "scanner_title" to "एआई फसल डॉक्टर",
            "take_photo" to "फोटो लें",
            "upload_gallery" to "गैलरी से अपलोड करें",
            "analyzing" to "छवि का विश्लेषण हो रहा है...",
            "chat_placeholder" to "NuKropAI से पूछें...",
            "chat_title" to "NuKropAI सहायक",
            "weather_alerts" to "बाजार और मौसम अलर्ट सक्रिय",
            "nav_autopilot" to "ऑटोपायलट",
            "nav_finance" to "वित्त",
            "good_farmer" to "शुभ %s, किसान!",
            "quick_actions" to "त्वरित कार्य",
            "scan_crop" to "फसल स्कैन",
            "ai_disease" to "एआई रोग एवं कीट पहचान",
            "scan_soil" to "मिट्टी स्कैन",
            "ai_soil" to "एआई मिट्टी स्वास्थ्य विश्लेषण",
            "market_rates_action" to "बाजार भाव",
            "live_mandi_prices" to "लाइव मंडी भाव",
            "ai_advisor" to "एआई सलाहकार",
            "ask_question" to "कोई भी कृषि प्रश्न पूछें",
            "loan_subsidy" to "ऋण एवं सब्सिडी",
            "govt_schemes" to "सरकारी योजना मैचर",
            "field_navigator" to "खेत नेविगेटर",
            "gps_route" to "GPS मार्ग एवं कवरेज",
            "my_tracked" to "मेरी ट्रैक की गई कीमतें",
            "pest_radar" to "हाइपरलोकल कीट पूर्वानुमान एआई",
            "high_risk" to "उच्च जोखिम",
            "report_outbreak" to "मेरे खेत में प्रकोप की रिपोर्ट करें",
            "outbreak_logged" to "प्रकोप दर्ज किया गया। पड़ोसी किसानों को सूचित किया!",
            "ai_tasks" to "एआई कार्य अनुसूची",
            "farm_tips" to "आज की कृषि सुझाव",
            "subsidy_title" to "सरकारी योजनाएं एआई",
            "ai_matcher" to "एआई योजना मैचर",
            "find_subsidies" to "मेरी सब्सिडी खोजें",
            "scanning_gov" to "सरकारी डेटाबेस स्कैन हो रहा है...",
            "outbreak_alerts_title" to "क्षेत्रीय प्रकोप अलर्ट",
            "outbreak_epicenter" to "केंद्रबिंदू प्रकोप",
            "outbreak_early_warning" to "प्रारंभिक चेतावनी अलर्ट",
            "no_active_alerts" to "आपके राज्य में कोई सक्रिय महामारी अलर्ट नहीं है",
            "grid_all_clear" to "राष्ट्रीय प्रकोप ग्रिड: स्कैन घनता सामान्य (7 दिनों में < 100 स्कैन)।",
            "view_market_impact" to "बाजार मूल्य प्रभाव देखें",
            "scan_density_trigger" to "घनता: %d स्कैन मिले (>%d सीमा)",
            "market_impact_title" to "प्रकोप बाजार मूल्य प्रभाव",
            "predicted_peak_price" to "अनुमानित उच्चतम मूल्य",
            "confidence_score" to "विश्वास स्कोर",
            "risk_level" to "जोखिम स्तर",
            "farmer_advisory" to "किसान कार्य सलाह",
            "affected_mandis" to "प्रभावित एपीएमसी मंडियां",
            "privacy_badge_title" to "राष्ट्रीय प्रकोप प्रारंभिक चेतावनी ग्रिड",
            "privacy_badge_desc" to "पड़ोसी किसानों की सुरक्षा के लिए अज्ञात स्कैन टेलीमेट्री सुरक्षित रूप से साझा की गई। कोई व्यक्तिगत पहचान साझा नहीं की गई।"
        ),
        "te" to mapOf(
            "nav_home" to "హోమ్",
            "market_rates" to "ప్రత్యక్ష మార్కెట్ ధరలు",
            "nav_market" to "మార్కెట్",
            "nav_scan" to "స్కాన్",
            "nav_chat" to "చాట్",
            "nav_profile" to "ప్రొఫైల్",
            "detecting" to "కనుగొంటోంది...",
            "auto_detect" to "ఆటో-డిటెక్ట్ లొకేషన్",
            "powered_by" to "డైరెక్ట్ అగ్మార్కెట్ ప్రభుత్వ API ఇంటిగ్రేషన్",
            "search_placeholder" to "పంట పేరు నమోదు చేయండి (ఉదా. టమోటా, గోధుమ...)",
            "search_btn" to "వెతకండి",
            "popular_crops" to "ప్రముఖ పంటలు",
            "fetching_live" to "ప్రభుత్వ API డేటాను పొందుతోంది...",
            "no_live_data" to "దీనికి ప్రత్యక్ష మార్కెట్ డేటా కనుగొనబడలేదు:",
            "try_different" to "వేరే పంట లేదా స్థానాన్ని ప్రయత్నించండి.",
            "mandi" to "మండీ",
            "modal_price" to "సగటు ధర (INR/క్వింటాల్)",
            "variety" to "రకం:",
            "min" to "కనిష్ట:",
            "max" to "గరిష్ట:",
            "track_price" to "🔔 ధరను ట్రాక్ చేయండి",
            "tracking_active" to "✅ ట్రాకింగ్ అవుతోంది",
            "edit_location" to "స్థానాన్ని సవరించండి",
            "enter_state" to "రాష్ట్రం (ఉదా. పంజాబ్)",
            "enter_mandi" to "మండీ (ఉదా. ఖన్నా)",
            "save" to "సేవ్ చేయి",
            "cancel" to "రద్దు చేయి",
            "scanner_title" to "AI పంట డాక్టర్",
            "take_photo" to "ఫోటో తీయండి",
            "upload_gallery" to "గ్యాలరీ నుండి అప్‌లోడ్ చేయండి",
            "analyzing" to "చిత్రాన్ని విశ్లేషిస్తోంది...",
            "chat_placeholder" to "NuKropAI ని అడగండి...",
            "chat_title" to "NuKropAI సహాయకుడు",
            "weather_alerts" to "మార్కెట్ & వాతావరణ హెచ్చరికలు యాక్టివ్‌గా ఉన్నాయి",
            "nav_autopilot" to "ఆటోపైలట్",
            "nav_finance" to "ఫైనాన్స్",
            "subsidy_title" to "ప్రభుత్వ పథకాలు AI",
            "ai_matcher" to "AI స్కీమ్ మ్యాచర్",
            "find_subsidies" to "నా సబ్సిడీలను కనుగొనండి",
            "scanning_gov" to "ప్రభుత్వ డేటాబేస్లను స్కాన్ చేస్తోంది...",
            "outbreak_alerts_title" to "ప్రాంతీయ వ్యాప్తి హెచ్చరికలు",
            "outbreak_epicenter" to "కేంద్రబిందువు వ్యాప్తి",
            "outbreak_early_warning" to "ముందస్తు హెచ్చరిక అలర్ట్",
            "no_active_alerts" to "మీ రాష్ట్రంలో క్రియాశీల వ్యాప్తి హెచ్చరికలు లేవు",
            "grid_all_clear" to "జాతీయ వ్యాప్తి గ్రిడ్: సాంద్రత సాధారణం (7 రోజుల్లో < 100 స్కాన్లు).",
            "view_market_impact" to "మార్కెట్ ధర ప్రభావాన్ని చూడండి",
            "scan_density_trigger" to "సాంద్రత: %d స్కాన్లు గుర్తించబడ్డాయి (>%d పరిమితి)",
            "market_impact_title" to "వ్యాప్తి మార్కెట్ ధర ప్రభావం",
            "predicted_peak_price" to "అంచనా వేసిన గరిష్ట ధర",
            "confidence_score" to "విశ్వాస స్కోరు",
            "risk_level" to "ప్రమాద స్థాయి",
            "farmer_advisory" to "రైతు కార్యాచరణ సలహా",
            "affected_mandis" to "ప్రభావిత APMC మండీలు",
            "privacy_badge_title" to "జాతీయ వ్యాప్తి ముందస్తు హెచ్చరిక గ్రిడ్",
            "privacy_badge_desc" to "పొరుగు రైతులను రక్షించడానికి అనామక స్కాన్ టెలిమెట్రీ అందించబడింది. వ్యక్తిగత సమాచారం భాగస్వామ్యం చేయబడదు."
        ),
        "ta" to mapOf(
            "nav_home" to "முகப்பு",
            "market_rates" to "நேரடி மண்டி விலைகள்",
            "nav_market" to "சந்தை",
            "nav_scan" to "ஸ்கேன்",
            "nav_chat" to "அரட்டை",
            "nav_profile" to "சுயவிவரம்",
            "detecting" to "கண்டறியப்படுகிறது...",
            "auto_detect" to "தானாக கண்டறியும் இடம்",
            "powered_by" to "நேரடி அக்மார்க்நெட் அரசு ஏபிஐ ஒருங்கிணைப்பு",
            "search_placeholder" to "பயிரை உள்ளிடவும் (எ.கா. தக்காளி, கோதுமை...)",
            "search_btn" to "தேடு",
            "popular_crops" to "பிரபலமான பயிர்கள்",
            "fetching_live" to "நேரடி அரசு ஏபிஐ தரவு பெறப்படுகிறது...",
            "no_live_data" to "இதற்கான நேரடி சந்தை தரவு எதுவும் கிடைக்கவில்லை:",
            "try_different" to "வேறு பயிர் அல்லது இடத்தை முயற்சிக்கவும்.",
            "mandi" to "மண்டி",
            "modal_price" to "சராசரி விலை (INR/குவிண்டால்)",
            "variety" to "வகை:",
            "min" to "குறைந்தபட்ச:",
            "max" to "அதிகபட்ச:",
            "track_price" to "🔔 விலையை கண்காணிக்கவும்",
            "tracking_active" to "✅ கண்காணிப்பில் உள்ளது",
            "edit_location" to "இடத்தைத் திருத்தவும்",
            "enter_state" to "மாநிலம் (எ.கா. பஞ்சாப்)",
            "enter_mandi" to "மண்டி (எ.கா. கண்ணா)",
            "save" to "சேமி",
            "cancel" to "ரத்துசெய்",
            "scanner_title" to "AI பயிர் மருத்துவர்",
            "take_photo" to "புகைப்படம் எடு",
            "upload_gallery" to "கேலரியில் இருந்து பதிவேற்றவும்",
            "analyzing" to "படம் பகுப்பாய்வு செய்யப்படுகிறது...",
            "chat_placeholder" to "NuKropAI இடம் கேளுங்கள்...",
            "chat_title" to "NuKropAI உதவியாளர்",
            "weather_alerts" to "சந்தை மற்றும் வானிலை எச்சரிக்கைகள் செயலில் உள்ளன",
            "nav_autopilot" to "ஆட்டோபைலட்",
            "nav_finance" to "நிதி",
            "subsidy_title" to "அரசு திட்டங்கள் AI",
            "ai_matcher" to "AI திட்ட மேட்சர்",
            "find_subsidies" to "எனது மானியங்களைக் கண்டறியுங்கள்",
            "scanning_gov" to "அரசு தரவுத்தளங்களை ஸ்கேன் செய்கிறது...",
            "outbreak_alerts_title" to "பிராந்திய நோய் வெடிப்பு எச்சரிக்கைகள்",
            "outbreak_epicenter" to "மையப்பகுதி நோய் வெடிப்பு",
            "outbreak_early_warning" to "முன்கூட்டியே எச்சரிக்கை",
            "no_active_alerts" to "உங்கள் மாநிலத்தில் செயலில் உள்ள நோய் வெடிப்பு எச்சரிக்கைகள் இல்லை",
            "grid_all_clear" to "தேசிய நோய் வெடிப்பு கட்டமைப்பு: அடர்த்தி இயல்பானது (7 நாட்களில் < 100 ஸ்கேன்கள்).",
            "view_market_impact" to "சந்தை விலை தாக்கத்தைப் பார்க்கவும்",
            "scan_density_trigger" to "அடர்த்தி: %d ஸ்கேன்கள் கண்டறியப்பட்டன (>%d வரம்பு)",
            "market_impact_title" to "நோய் வெடிப்பு சந்தை விலை தாக்கம்",
            "predicted_peak_price" to "கணிக்கப்பட்ட உச்ச விலை",
            "confidence_score" to "நம்பகத்தன்மை மதிப்பீடு",
            "risk_level" to "ஆபத்து நிலை",
            "farmer_advisory" to "விவசாயி செயல் ஆலோசனை",
            "affected_mandis" to "பாதிக்கப்பட்ட ஏபிஎம்சி மண்டிகள்",
            "privacy_badge_title" to "தேசிய நோய் வெடிப்பு முன்கூட்டிய எச்சரிக்கை கட்டமைப்பு",
            "privacy_badge_desc" to "அண்டை விவசாயிகளைப் பாதுகாக்க அநாமதேய ஸ்கேன் டெலிமெட்ரி பாதுகாப்பாக வழங்கப்பட்டது."
        ),
        "mr" to mapOf(
            "nav_home" to "होम",
            "market_rates" to "थेट बाजार भाव",
            "nav_market" to "बाजार",
            "nav_scan" to "स्कॅन",
            "nav_chat" to "चॅट",
            "nav_profile" to "प्रोफाइल",
            "detecting" to "शोधत आहे...",
            "auto_detect" to "स्थान स्वयंचलित शोधा",
            "powered_by" to "थेट एगमार्कनेट सरकारी एपीआय एकत्रीकरण",
            "search_placeholder" to "पीक प्रविष्ट करा (उदा. टोमॅटो, गहू...)",
            "search_btn" to "शोधा",
            "popular_crops" to "लोकप्रिय पिके",
            "fetching_live" to "थेट सरकारी एपीआय डेटा मिळवत आहे...",
            "no_live_data" to "यासाठी थेट बाजार डेटा आढळला नाही:",
            "try_different" to "वेगळे पीक किंवा स्थान वापरून पहा.",
            "mandi" to "मंडी",
            "modal_price" to "सरासरी किंमत (INR/क्विंटल)",
            "variety" to "जात:",
            "min" to "किमान:",
            "max" to "कमाल:",
            "track_price" to "🔔 किंमत ट्रॅक करा",
            "tracking_active" to "✅ ट्रॅकिंग सक्रिय",
            "edit_location" to "स्थान बदला",
            "enter_state" to "राज्य (उदा. पंजाब)",
            "enter_mandi" to "मंडी (उदा. खन्ना)",
            "save" to "जतन करा",
            "cancel" to "रद्द करा",
            "scanner_title" to "एआई पीक डॉक्टर",
            "take_photo" to "फोटो काढा",
            "upload_gallery" to "गॅलरीमधून अपलोड करा",
            "analyzing" to "प्रतिमेचे विश्लेषण करत आहे...",
            "chat_placeholder" to "NuKropAI ला विचारा...",
            "chat_title" to "NuKropAI सहाय्यक",
            "weather_alerts" to "बाजार आणि हवामान सूचना सक्रिय",
            "nav_autopilot" to "ऑटोपायलट",
            "nav_finance" to "वित्त",
            "subsidy_title" to "सरकारी योजना AI",
            "ai_matcher" to "AI योजना मॅचर",
            "find_subsidies" to "माझे अनुदान शोधा",
            "scanning_gov" to "सरकारी डेटाबेस स्कॅन होत आहे...",
            "outbreak_alerts_title" to "प्रादेशिक उद्रेक सूचना",
            "outbreak_epicenter" to "केंद्रबिंदू उद्रेक",
            "outbreak_early_warning" to "पूर्वसूचना अलर्ट",
            "no_active_alerts" to "तुमच्या राज्यात कोणतीही सक्रिय उद्रेक सूचना नाही",
            "grid_all_clear" to "राष्ट्रीय उद्रेक ग्रिड: स्कॅन घनता सामान्य (7 दिवसांत < 100 स्कॅन).",
            "view_market_impact" to "बाजारभाव प्रभाव पहा",
            "scan_density_trigger" to "घनता: %d स्कॅन आढळले (>%d मर्यादा)",
            "market_impact_title" to "उद्रेक बाजारभाव प्रभाव",
            "predicted_peak_price" to "अंदाजित कमाल भाव",
            "confidence_score" to "विश्वासार्हता धावसंख्या",
            "risk_level" to "धोका पातळी",
            "farmer_advisory" to "शेतकरी कृती सल्ला",
            "affected_mandis" to "प्रभावित एपीएमसी बाजार",
            "privacy_badge_title" to "राष्ट्रीय उद्रेक पूर्वसूचना ग्रिड",
            "privacy_badge_desc" to "शेजारील शेतकऱ्यांच्या संरक्षणासाठी निनावी स्कॅन टेलिमेट्री सुरक्षितपणे दिली. कोणताही वैयक्तिक डेटा सामायिक केलेला नाही."
        ),
        "kn" to mapOf(
            "nav_home" to "ಮುಖಪುಟ",
            "market_rates" to "ನೇರ ಮಾರುಕಟ್ಟೆ ದರಗಳು",
            "nav_market" to "ಮಾರುಕಟ್ಟೆ",
            "nav_scan" to "ಸ್ಕ್ಯಾನ್",
            "nav_chat" to "ಚಾಟ್",
            "nav_profile" to "ಪ್ರೊಫೈಲ್",
            "detecting" to "ಪತ್ತೆಹಚ್ಚಲಾಗುತ್ತಿದೆ...",
            "auto_detect" to "ಸ್ವಯಂ ಪತ್ತೆ ಸ್ಥಳ",
            "powered_by" to "ಅಗ್ಮಾರ್ಕ್ನೆಟ್ ಸರ್ಕಾರದ API ಏಕೀಕರಣ",
            "search_placeholder" to "ಬೆಳೆ ನಮೂದಿಸಿ (ಉದಾ. ಟೊಮೆಟೊ, ಗೋಧಿ...)",
            "search_btn" to "ಹುಡುಕಿ",
            "popular_crops" to "ಜನಪ್ರಿಯ ಬೆಳೆಗಳು",
            "fetching_live" to "ನೇರ ಸರ್ಕಾರದ API ಡೇಟಾ ಪಡೆಯಲಾಗುತ್ತಿದೆ...",
            "no_live_data" to "ನೇರ ಮಾರುಕಟ್ಟೆ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ:",
            "try_different" to "ಬೇರೆ ಬೆಳೆ ಅಥವಾ ಸ್ಥಳವನ್ನು ಪ್ರಯತ್ನಿಸಿ.",
            "mandi" to "ಮಂಡಿ",
            "modal_price" to "ಸರಾಸರಿ ಬೆಲೆ (INR/ಕ್ವಿಂಟಾಲ್)",
            "variety" to "ತಳಿ:",
            "min" to "ಕನಿಷ್ಠ:",
            "max" to "ಗರಿಷ್ಠ:",
            "track_price" to "🔔 ಬೆಲೆ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
            "tracking_active" to "✅ ಟ್ರ್ಯಾಕಿಂಗ್ ಸಕ್ರಿಯವಾಗಿದೆ",
            "edit_location" to "ಸ್ಥಳ ಬದಲಾಯಿಸಿ",
            "enter_state" to "ರಾಜ್ಯ (ಉದಾ. ಪಂಜಾಬ್)",
            "enter_mandi" to "ಮಂಡಿ (ಉದಾ. ಖನ್ನಾ)",
            "save" to "ಉಳಿಸಿ",
            "cancel" to "ರದ್ದುಮಾಡಿ",
            "scanner_title" to "AI ಬೆಳೆ ವೈದ್ಯ",
            "take_photo" to "ಫೋಟೋ ತೆಗೆಯಿರಿ",
            "upload_gallery" to "ಗ್ಯಾಲರಿಯಿಂದ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
            "analyzing" to "ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
            "chat_placeholder" to "NuKropAI ಗೆ ಕೇಳಿ...",
            "chat_title" to "NuKropAI ಸಹಾಯಕ",
            "weather_alerts" to "ಮಾರುಕಟ್ಟೆ ಮತ್ತು ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳು",
            "nav_autopilot" to "ಆಟೋಪೈಲಟ್",
            "nav_finance" to "ಹಣಕಾಸು",
            "subsidy_title" to "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು AI",
            "ai_matcher" to "AI ಯೋಜನೆ ಮ್ಯಾಚರ್",
            "find_subsidies" to "ನನ್ನ ಸಬ್ಸಿಡಿಗಳನ್ನು ಹುಡುಕಿ",
            "scanning_gov" to "ಸರ್ಕಾರಿ ಡೇಟಾಬೇಸ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
            "outbreak_alerts_title" to "ಪ್ರಾದೇಶಿಕ ರೋಗ ಹರಡುವಿಕೆ ಎಚ್ಚರಿಕೆಗಳು",
            "outbreak_epicenter" to "ಕೇಂದ್ರಬಿಂದು ರೋಗ ಹರಡುವಿಕೆ",
            "outbreak_early_warning" to "ಮುನ್ಸೂಚನೆ ಎಚ್ಚರಿಕೆ",
            "no_active_alerts" to "ನಿಮ್ಮ ರಾಜ್ಯದಲ್ಲಿ ಯಾವುದೇ ಸಕ್ರಿಯ ರೋಗ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ",
            "grid_all_clear" to "ರಾಷ್ಟ್ರೀಯ ರೋಗ ಗ್ರಿಡ್: ಸ್ಕ್ಯಾನ್ ಸಾಂದ್ರತೆ ಸಾಮಾನ್ಯವಾಗಿದೆ.",
            "view_market_impact" to "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಪರಿಣಾಮ ನೋಡಿ",
            "scan_density_trigger" to "ಸಾಂದ್ರತೆ: %d ಸ್ಕ್ಯಾನ್‌ಗಳು ಪತ್ತೆಯಾಗಿವೆ",
            "market_impact_title" to "ರೋಗ ಹರಡುವಿಕೆ ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಪರಿಣಾಮ",
            "predicted_peak_price" to "ಅಂದಾಜು ಗರಿಷ್ಠ ಬೆಲೆ",
            "confidence_score" to "ವಿಶ್ವಾಸಾರ್ಹತೆ ಸ್ಕೋರ್",
            "risk_level" to "ಅಪಾಯ ಮಟ್ಟ",
            "farmer_advisory" to "ರೈತರ ಕ್ರಿಯಾ ಸಲಹೆ",
            "affected_mandis" to "ಬಾಧಿತ APMC ಮಂಡಿಗಳು",
            "privacy_badge_title" to "ರಾಷ್ಟ್ರೀಯ ಮುನ್ಸೂಚನೆ ಗ್ರಿಡ್",
            "privacy_badge_desc" to "ನೆರೆಹೊರೆಯ ರೈತರ ರಕ್ಷಣೆಗಾಗಿ ಅನಾಮಧೇಯ ಸ್ಕ್ಯಾನ್ ಟೆಲಿಮೆಟ್ರಿ ಸುರಕ್ಷಿತವಾಗಿ ಒದಗಿಸಲಾಗಿದೆ."
        ),
        "ml" to mapOf(
            "nav_home" to "ഹോം",
            "market_rates" to "തത്സമയ മാർക്കറ്റ് നിരക്കുകൾ",
            "nav_market" to "മാർക്കറ്റ്",
            "nav_scan" to "സ്കാൻ",
            "nav_chat" to "ചാറ്റ്",
            "nav_profile" to "പ്രൊഫൈൽ",
            "detecting" to "കണ്ടെത്തുന്നു...",
            "auto_detect" to "ലൊക്കേഷൻ സ്വയം കണ്ടെത്തുക",
            "powered_by" to "അഗ്മാർക്ക്നെറ്റ് ഗവൺമെന്റ് API സംയോജനം",
            "search_placeholder" to "വിള നൽകുക (ഉദാ. തക്കാളി, ഗോതമ്പ്...)",
            "search_btn" to "തിരയുക",
            "popular_crops" to "ജനപ്രിയ വിളകൾ",
            "fetching_live" to "തത്സമയ ഗവൺമെന്റ് API ഡാറ്റ എടുക്കുന്നു...",
            "no_live_data" to "തത്സമയ മാർക്കറ്റ് ഡാറ്റ ലഭ്യമല്ല:",
            "try_different" to "മറ്റൊരു വിളയോ സ്ഥലമോ പരീക്ഷിക്കുക.",
            "mandi" to "മാർക്കറ്റ്",
            "modal_price" to "ശരാശരി വില (INR/ക്വിന്റൽ)",
            "variety" to "ഇനം:",
            "min" to "കുറഞ്ഞത്:",
            "max" to "കൂടിയത്:",
            "track_price" to "🔔 വില നിരീക്ഷിക്കുക",
            "tracking_active" to "✅ ട്രാക്കിംഗ് സജീവം",
            "edit_location" to "സ്ഥലം മാറ്റുക",
            "enter_state" to "സംസ്ഥാനം (ഉദാ. പഞ്ചാബ്)",
            "enter_mandi" to "മാർക്കറ്റ് (ഉദാ. ഖന്ന)",
            "save" to "സംരക്ഷിക്കുക",
            "cancel" to "റദ്ദാക്കുക",
            "scanner_title" to "AI വിള ഡോക്ടർ",
            "take_photo" to "ഫോട്ടോ എടുക്കുക",
            "upload_gallery" to "ഗ്യാലറിയിൽ നിന്ന് അപ്‌ലോഡ് ചെയ്യുക",
            "analyzing" to "ചിത്രം വിശകലനം ചെയ്യുന്നു...",
            "chat_placeholder" to "NuKropAI യോട് ചോദിക്കൂ...",
            "chat_title" to "NuKropAI സഹായി",
            "weather_alerts" to "മാർക്കറ്റ് കാലാവസ്ഥാ മുന്നറിയിപ്പുകൾ",
            "nav_autopilot" to "ഓട്ടോപൈലറ്റ്",
            "nav_finance" to "ധനകാര്യം",
            "subsidy_title" to "സർക്കാർ പദ്ധതികൾ AI",
            "ai_matcher" to "AI സ്കീം മാച്ചർ",
            "find_subsidies" to "എന്റെ സബ്‌സിഡികൾ കണ്ടെത്തുക",
            "scanning_gov" to "സർക്കാർ ഡാറ്റാബേസുകൾ സ്കാൻ ചെയ്യുന്നു...",
            "outbreak_alerts_title" to "പ്രാദേശിക രോഗബാധ മുന്നറിയിപ്പുകൾ",
            "outbreak_epicenter" to "പ്രഭവകേന്ദ്രം രോഗബാധ",
            "outbreak_early_warning" to "മുൻകൂർ മുന്നറിയിപ്പ്",
            "no_active_alerts" to "നിങ്ങളുടെ സംസ്ഥാനത്ത് സജീവമായ മുന്നറിയിപ്പുകൾ ഇല്ല",
            "grid_all_clear" to "ദേശീയ രോഗബാധ ഗ്രിഡ്: സാധാരണ നിലയിലുള്ള സ്കാൻ സാന്ദ്രത.",
            "view_market_impact" to "മാർക്കറ്റ് വില ആഘാതം കാണുക",
            "scan_density_trigger" to "സാന്ദ്രത: %d സ്കാനുകൾ കണ്ടെത്തി",
            "market_impact_title" to "രോഗബാധ മാർക്കറ്റ് വില ആഘാതം",
            "predicted_peak_price" to "പ്രതീക്ഷിക്കുന്ന ഉയർന്ന വില",
            "confidence_score" to "വിശ്വാസ്യത സ്കോർ",
            "risk_level" to "അപകടസാധ്യത നില",
            "farmer_advisory" to "കർഷക കർമ്മ നിർദ്ദേശം",
            "affected_mandis" to "ബാധിച്ച APMC മാർക്കറ്റുകൾ",
            "privacy_badge_title" to "ദേശീയ മുൻകൂർ മുന്നറിയിപ്പ് ഗ്രിഡ്",
            "privacy_badge_desc" to "കർഷകരുടെ സംരക്ഷണത്തിനായി വ്യക്തിഗത വിവരങ്ങൾ ഇല്ലാതെ സ്കാൻ ടെലിമെട്രി സുരക്ഷിതമായി നൽകി."
        ),
        "bn" to mapOf(
            "nav_home" to "হোম",
            "market_rates" to "লাইভ মান্ডি দর",
            "nav_market" to "বাজার",
            "nav_scan" to "স্ক্যান",
            "nav_chat" to "চ্যাট",
            "nav_profile" to "প্রোফাইল",
            "detecting" to "শনাক্ত করা হচ্ছে...",
            "auto_detect" to "স্বয়ংক্রিয় অবস্থান শনাক্তকরণ",
            "powered_by" to "অ্যাগমার্কনেট সরকারি এপিআই ইন্টিগ্রেশন",
            "search_placeholder" to "ফসল লিখুন (যেমন টমেটো, গম...)",
            "search_btn" to "অনুসন্ধান",
            "popular_crops" to "জনপ্রিয় ফসল",
            "fetching_live" to "লাইভ সরকারি এপিআই তথ্য সংগ্রহ করা হচ্ছে...",
            "no_live_data" to "কোনো লাইভ বাজার তথ্য পাওয়া যায়নি:",
            "try_different" to "অন্য কোনো ফসল বা অবস্থান চেষ্টা করুন।",
            "mandi" to "মান্ডি",
            "modal_price" to "গড় মূল্য (INR/কুইন্টাল)",
            "variety" to "জাত:",
            "min" to "সর্বনিম্ন:",
            "max" to "সর্বোচ্চ:",
            "track_price" to "🔔 দাম ট্র্যাক করুন",
            "tracking_active" to "✅ ট্র্যাকিং সক্রিয়",
            "edit_location" to "অবস্থান পরিবর্তন করুন",
            "enter_state" to "রাজ্য (যেমন পাঞ্জাব)",
            "enter_mandi" to "মান্ডি (যেমন খান্না)",
            "save" to "সংরক্ষণ করুন",
            "cancel" to "বাতিল করুন",
            "scanner_title" to "এআই ফসল ডাক্তার",
            "take_photo" to "ছবি তুলুন",
            "upload_gallery" to "গ্যালারি থেকে আপলোড করুন",
            "analyzing" to "ছবি বিশ্লেষণ করা হচ্ছে...",
            "chat_placeholder" to "NuKropAI কে জিজ্ঞাসা করুন...",
            "chat_title" to "NuKropAI সহায়ক",
            "weather_alerts" to "বাজার এবং আবহাওয়া সতর্কতা সক্রিয়",
            "nav_autopilot" to "অটোপাইলট",
            "nav_finance" to "অর্থসংস্থান",
            "subsidy_title" to "সরকারি প্রকল্প এআই",
            "ai_matcher" to "এআই প্রকল্প ম্যাচিং",
            "find_subsidies" to "আমার ভর্তুকি খুঁজুন",
            "scanning_gov" to "সরকারি ডাটাবেস স্ক্যান করা হচ্ছে...",
            "outbreak_alerts_title" to "আঞ্চলিক প্রাদুর্ভাব সতর্কতা",
            "outbreak_epicenter" to "কেন্দ্রবিন্দু প্রাদুর্ভাব",
            "outbreak_early_warning" to "আগাম সতর্কতা",
            "no_active_alerts" to "আপনার রাজ্যে কোনো সক্রিয় প্রাদুর্ভাব সতর্কতা নেই",
            "grid_all_clear" to "জাতীয় প্রাদুর্ভাব গ্রিড: স্ক্যান ঘনত্ব স্বাভাবিক।",
            "view_market_impact" to "বাজার মূল্যের প্রভাব দেখুন",
            "scan_density_trigger" to "ঘনত্ব: %d স্ক্যান শনাক্ত হয়েছে",
            "market_impact_title" to "প্রাদুর্ভাব বাজার মূল্যের প্রভাব",
            "predicted_peak_price" to "আনুমানিক সর্বোচ্চ মূল্য",
            "confidence_score" to "নির্ভরযোগ্যতা স্কোর",
            "risk_level" to "ঝুঁকির মাত্রা",
            "farmer_advisory" to "কৃষক কর্মপদ্ধতি পরামর্শ",
            "affected_mandis" to "ক্ষতিগ্রস্ত এপিএমসি মান্ডি",
            "privacy_badge_title" to "জাতীয় আগাম সতর্কতা গ্রিড",
            "privacy_badge_desc" to "প্রতিবেশী কৃষকদের সুরক্ষার জন্য বেনামী স্ক্যান টেলিমেট্রি প্রদান করা হয়েছে। কোনো ব্যক্তিগত তথ্য শেয়ার করা হয়নি।"
        ),
        "gu" to mapOf(
            "nav_home" to "હોમ",
            "market_rates" to "લાઇવ માર્કેટ ભાવ",
            "nav_market" to "બજાર",
            "nav_scan" to "સ્કેન",
            "nav_chat" to "ચેટ",
            "nav_profile" to "પ્રોફાઇલ",
            "detecting" to "શોધી રહ્યું છે...",
            "auto_detect" to "સ્થાન આપોઆપ શોધો",
            "powered_by" to "ડાયરેક્ટ એગમાર્કનેટ સરકારી API",
            "search_placeholder" to "પાક દાખલ કરો (દા.ત. ટામેટા, ઘઉં...)",
            "search_btn" to "શોધો",
            "popular_crops" to "લોકપ્રિય પાકો",
            "fetching_live" to "સરકારી API ડેટા મેળવી રહ્યું છે...",
            "no_live_data" to "કોઈ લાઈવ માર્કેટ ડેટા મળ્યો નથી:",
            "try_different" to "અન્ય પાક અથવા સ્થાન અજમાવો.",
            "mandi" to "માર્કેટ યાર્ડ",
            "modal_price" to "સરેરાશ ભાવ (INR/ક્વિન્ટલ)",
            "variety" to "જાત:",
            "min" to "ન્યૂનતમ:",
            "max" to "મહત્તમ:",
            "track_price" to "🔔 ભાવ ટ્રેક કરો",
            "tracking_active" to "✅ ટ્રેકિંગ સક્રિય",
            "edit_location" to "સ્થાન બદલો",
            "enter_state" to "રાજ્ય (દા.ત. પંજાબ)",
            "enter_mandi" to "યાર્ડ (દા.ત. ખન્ના)",
            "save" to "સાચવો",
            "cancel" to "રદ કરો",
            "scanner_title" to "AI પાક ડૉક્ટર",
            "take_photo" to "ફોટો લો",
            "upload_gallery" to "ગેલેરીમાંથી અપલોડ કરો",
            "analyzing" to "છબીનું વિશ્લેષણ થઈ રહ્યું છે...",
            "chat_placeholder" to "NuKropAI ને પૂછો...",
            "chat_title" to "NuKropAI સહાયક",
            "weather_alerts" to "બજાર અને હવામાન ચેતવણીઓ",
            "nav_autopilot" to "ઓટોપાયલટ",
            "nav_finance" to "નાણાકીય સહાય",
            "subsidy_title" to "સરકારી યોજનાઓ AI",
            "ai_matcher" to "AI યોજના મેચર",
            "find_subsidies" to "મારી સબસિડી શોધો",
            "scanning_gov" to "સરકારી ડેટાબેઝ સ્કેન થઈ રહ્યો છે...",
            "outbreak_alerts_title" to "પ્રાદેશિક રોગચાળો ચેતવણીઓ",
            "outbreak_epicenter" to "કેન્દ્રબિંદુ રોગચાળો",
            "outbreak_early_warning" to "પ્રારંભિક ચેતવણી",
            "no_active_alerts" to "તમારા રાજ્યમાં કોઈ સક્રિય ચેતવણી નથી",
            "grid_all_clear" to "રાષ્ટ્રીય ગ્રીડ: સ્કેન ઘનતા સામાન્ય છે.",
            "view_market_impact" to "બજાર ભાવ અસર જુઓ",
            "scan_density_trigger" to "ઘનતા: %d સ્કેન મળ્યા",
            "market_impact_title" to "રોગચાળો બજાર ભાવ અસર",
            "predicted_peak_price" to "અંદાજિત મહત્તમ ભાવ",
            "confidence_score" to "વિશ્વાસ સ્કોર",
            "risk_level" to "જોખમ સ્તર",
            "farmer_advisory" to "ખેડૂત સલાહ",
            "affected_mandis" to "અસરગ્રસ્ત APMC માર્કેટ",
            "privacy_badge_title" to "રાષ્ટ્રીય પ્રારંભિક ચેતવણી ગ્રીડ",
            "privacy_badge_desc" to "સાથી ખેડૂતોના રક્ષણ માટે અનામી સ્કેન ટેલિમેટ્રી સુરક્ષિત રીતે શેર કરવામાં આવી છે."
        ),
        "pa" to mapOf(
            "nav_home" to "ਮੁੱਖ ਪੰਨਾ",
            "market_rates" to "ਲਾਈਵ ਮੰਡੀ ਭਾਅ",
            "nav_market" to "ਮੰਡੀ",
            "nav_scan" to "ਸਕੈਨ",
            "nav_chat" to "ਗੱਲਬਾਤ",
            "nav_profile" to "ਪ੍ਰੋਫਾਈਲ",
            "detecting" to "ਖੋਜ ਰਿਹਾ ਹੈ...",
            "auto_detect" to "ਸਥਾਨ ਆਪਣੇ ਆਪ ਖੋਜੋ",
            "powered_by" to "ਸਿੱਧਾ ਐਗਮਾਰਕਨੇਟ ਸਰਕਾਰੀ API ਏਕੀਕਰਣ",
            "search_placeholder" to "ਫ਼ਸਲ ਦਰਜ ਕਰੋ (ਜਿਵੇਂ ਟਮਾਟਰ, ਕਣਕ...)",
            "search_btn" to "ਖੋਜੋ",
            "popular_crops" to "ਪ੍ਰਸਿੱਧ ਫ਼ਸਲਾਂ",
            "fetching_live" to "ਲਾਈਵ ਸਰਕਾਰੀ API ਡਾਟਾ ਪ੍ਰਾਪਤ ਕਰ ਰਿਹਾ ਹੈ...",
            "no_live_data" to "ਇਸ ਲਈ ਕੋਈ ਲਾਈਵ ਮੰਡੀ ਡਾਟਾ ਨਹੀਂ ਮਿਲਿਆ:",
            "try_different" to "ਕੋਈ ਹੋਰ ਫ਼ਸਲ ਜਾਂ ਸਥਾਨ ਅਜ਼ਮਾਓ।",
            "mandi" to "ਮੰਡੀ",
            "modal_price" to "ਔਸਤ ਭਾਅ (INR/ਕਵਿੰਟਲ)",
            "variety" to "ਕਿਸਮ:",
            "min" to "ਘੱਟੋ-ਘੱਟ:",
            "max" to "ਵੱਧ ਤੋਂ ਵੱਧ:",
            "track_price" to "🔔 ਭਾਅ ਟਰੈਕ ਕਰੋ",
            "tracking_active" to "✅ ਟਰੈਕਿੰਗ ਚਾਲੂ ਹੈ",
            "edit_location" to "ਸਥਾਨ ਬਦਲੋ",
            "enter_state" to "ਰਾਜ (ਜਿਵੇਂ ਪੰਜਾਬ)",
            "enter_mandi" to "ਮੰਡੀ (ਜਿਵੇਂ ਖੰਨਾ)",
            "save" to "ਸੰਭਾਲੋ",
            "cancel" to "ਰੱਦ ਕਰੋ",
            "scanner_title" to "AI ਫ਼ਸਲ ਡਾਕਟਰ",
            "take_photo" to "ਫੋਟੋ ਖਿੱਚੋ",
            "upload_gallery" to "ਗੈਲਰੀ ਤੋਂ ਅੱਪਲੋਡ ਕਰੋ",
            "analyzing" to "ਤਸਵੀਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
            "chat_placeholder" to "NuKropAI ਤੋਂ ਪੁੱਛੋ...",
            "chat_title" to "NuKropAI ਸਹਾਇਕ",
            "weather_alerts" to "ਮੰਡੀ ਅਤੇ ਮੌਸਮ ਅਲਰਟ ਸਰਗਰਮ ਹਨ",
            "nav_autopilot" to "ਆਟੋਪਾਇਲਟ",
            "nav_finance" to "ਵਿੱਤ",
            "subsidy_title" to "ਸਰਕਾਰੀ ਸਕੀਮਾਂ AI",
            "ai_matcher" to "AI ਸਕੀਮ ਮੈਚਰ",
            "find_subsidies" to "ਮੇਰੀਆਂ ਸਬਸਿਡੀਆਂ ਲੱਭੋ",
            "scanning_gov" to "ਸਰਕਾਰੀ ਡਾਟਾਬੇਸ ਸਕੈਨ ਹੋ ਰਹੇ ਹਨ...",
            "outbreak_alerts_title" to "ਖੇਤਰੀ ਬਿਮਾਰੀ ਫੈਲਣ ਦੇ ਅਲਰਟ",
            "outbreak_epicenter" to "ਕੇਂਦਰ ਬਿੰਦੂ ਬਿਮਾਰੀ",
            "outbreak_early_warning" to "ਮੁੱਢਲੀ ਚੇਤਾਵਨੀ ਅਲਰਟ",
            "no_active_alerts" to "ਤੁਹਾਡੇ ਰਾਜ ਵਿੱਚ ਕੋਈ ਸਰਗਰਮ ਬਿਮਾਰੀ ਅਲਰਟ ਨਹੀਂ ਹੈ",
            "grid_all_clear" to "ਰਾਸ਼ਟਰੀ ਗਰਿੱਡ: ਸਕੈਨ ਘਣਤਾ ਆਮ ਹੈ।",
            "view_market_impact" to "ਮੰਡੀ ਭਾਅ ਪ੍ਰਭਾਵ ਦੇਖੋ",
            "scan_density_trigger" to "ਘਣਤਾ: %d ਸਕੈਨ ਮਿਲੇ",
            "market_impact_title" to "ਬਿਮਾਰੀ ਮੰਡੀ ਭਾਅ ਪ੍ਰਭਾਵ",
            "predicted_peak_price" to "ਅਨੁਮਾਨਿਤ ਸਿਖਰ ਭਾਅ",
            "confidence_score" to "ਭਰੋਸੇਯੋਗਤਾ ਸਕੋਰ",
            "risk_level" to "ਖ਼ਤਰੇ ਦਾ ਪੱਧਰ",
            "farmer_advisory" to "ਕਿਸਾਨ ਕਾਰਵਾਈ ਸਲਾਹ",
            "affected_mandis" to "ਪ੍ਰਭਾਵਿਤ APMC ਮੰਡੀਆਂ",
            "privacy_badge_title" to "ਰਾਸ਼ਟਰੀ ਮੁੱਢਲੀ ਚੇਤਾਵਨੀ ਗਰਿੱਡ",
            "privacy_badge_desc" to "ਗੁਆਂਢੀ ਕਿਸਾਨਾਂ ਦੀ ਸੁਰੱਖਿਆ ਲਈ ਅਗਿਆਤ ਸਕੈਨ ਟੈਲੀਮੈਟਰੀ ਸਾਂਝੀ ਕੀਤੀ ਗਈ ਹੈ।"
        ),
        "or" to mapOf(
            "nav_home" to "ମୁଖ୍ୟ ପୃଷ୍ଠା",
            "market_rates" to "ଲାଇଭ୍ ମଣ୍ଡି ଦର",
            "nav_market" to "ବଜାର",
            "nav_scan" to "ସ୍କାନ୍",
            "nav_chat" to "ଚାଟ୍",
            "nav_profile" to "ପ୍ରୋଫାଇଲ୍",
            "detecting" to "ଚିହ୍ନଟ ହେଉଛି...",
            "auto_detect" to "ସ୍ୱୟଂ ଚିହ୍ନଟ ସ୍ଥାନ",
            "powered_by" to "ଆଗମାର୍କନେଟ୍ ସରକାରୀ API ସଂଯୋଗ",
            "search_placeholder" to "ଫସଲ ନାମ ଲେଖନ୍ତୁ (ଯଥା: ଟମାଟୋ, ଗହମ...)",
            "search_btn" to "ଖୋଜନ୍ତୁ",
            "popular_crops" to "ଲୋକପ୍ରିୟ ଫସଲ",
            "fetching_live" to "ଲାଇଭ୍ ସରକାରୀ API ତଥ୍ୟ ସଂଗ୍ରହ ହେଉଛି...",
            "no_live_data" to "କୌଣସି ଲାଇଭ୍ ବଜାର ତଥ୍ୟ ମିଳିଲା ନାହିଁ:",
            "try_different" to "ଅନ୍ୟ ଏକ ଫସଲ କିମ୍ବା ସ୍ଥାନ ଚେଷ୍ଟା କରନ୍ତୁ।",
            "mandi" to "ମଣ୍ଡି",
            "modal_price" to "ହାରାହାରି ମୂଲ୍ୟ (INR/କ୍ୱିଣ୍ଟାଲ)",
            "variety" to "କିସମ:",
            "min" to "ସର୍ବନିମ୍ନ:",
            "max" to "ସର୍ବାଧିକ:",
            "track_price" to "🔔 ମୂଲ୍ୟ ଟ୍ରାକ୍ କରନ୍ତୁ",
            "tracking_active" to "✅ ଟ୍ରାକିଂ ସକ୍ରିୟ ଅଛି",
            "edit_location" to "ସ୍ଥାନ ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
            "enter_state" to "ରାଜ୍ୟ (ଯଥା: ପଞ୍ଜାବ)",
            "enter_mandi" to "ମଣ୍ଡି (ଯଥା: ଖାନ୍ନା)",
            "save" to "ସାଇତନ୍ତୁ",
            "cancel" to "ବାତିଲ୍ କରନ୍ତୁ",
            "scanner_title" to "AI ଫସଲ ଡାକ୍ତର",
            "take_photo" to "ଫଟୋ ଉଠାନ୍ତୁ",
            "upload_gallery" to "ଗ୍ୟାଲେରୀରୁ ଅପଲୋଡ୍ କରନ୍ତୁ",
            "analyzing" to "ଚିତ୍ର ବିଶ୍ଳେଷଣ ହେଉଛି...",
            "chat_placeholder" to "NuKropAI କୁ ପଚାରନ୍ତୁ...",
            "chat_title" to "NuKropAI ସହାୟକ",
            "weather_alerts" to "ବଜାର ଏବଂ ପାଣିପାଗ ସତର୍କତା ସକ୍ରିୟ",
            "nav_autopilot" to "ଅଟୋପାଇଲଟ୍",
            "nav_finance" to "ଆର୍ଥିକ ସହାୟତା",
            "subsidy_title" to "ସରକାରୀ ଯୋଜନା AI",
            "ai_matcher" to "AI ଯୋଜନା ମ୍ୟାଚର୍",
            "find_subsidies" to "ମୋର ସବସିଡି ଖୋଜନ୍ତୁ",
            "scanning_gov" to "ସରକାରୀ ଡାଟାବେସ୍ ସ୍କାନ୍ ହେଉଛି...",
            "outbreak_alerts_title" to "ଆଞ୍ଚଳିକ ରୋଗ ପ୍ରାଦୁର୍ଭାବ ସତର୍କତା",
            "outbreak_epicenter" to "କେନ୍ଦ୍ରବିନ୍ଦୁ ପ୍ରାଦୁର୍ଭାବ",
            "outbreak_early_warning" to "ପୂର୍ବ ସତର୍କତା",
            "no_active_alerts" to "ଆପଣଙ୍କ ରାଜ୍ୟରେ କୌଣସି ସକ୍ରିୟ ସତର୍କତା ନାହିଁ",
            "grid_all_clear" to "ଜାତୀୟ ପ୍ରାଦୁର୍ଭାବ ଗ୍ରିଡ୍: ସ୍କାନ୍ ସାନ୍ଦ୍ରତା ସାଧାରଣ।",
            "view_market_impact" to "ବଜାର ମୂଲ୍ୟ ପ୍ରଭାବ ଦେଖନ୍ତୁ",
            "scan_density_trigger" to "ସାନ୍ଦ୍ରତା: %d ସ୍କାନ୍ ଚିହ୍ନଟ ହୋଇଛି",
            "market_impact_title" to "ପ୍ରାଦୁର୍ଭାବ ବଜାର ମୂଲ୍ୟ ପ୍ରଭାବ",
            "predicted_peak_price" to "ଅନୁମାନିତ ସର୍ବୋଚ୍ଚ ମୂଲ୍ୟ",
            "confidence_score" to "ବିଶ୍ୱାସନୀୟତା ସ୍କୋର",
            "risk_level" to "ବିପଦ ସ୍ତର",
            "farmer_advisory" to "କୃଷକ କାର୍ଯ୍ୟ ପରାମର୍ଶ",
            "affected_mandis" to "ପ୍ରଭାବିତ APMC ମଣ୍ଡି",
            "privacy_badge_title" to "ଜାତୀୟ ପୂର୍ବ ସତର୍କତା ଗ୍ରିଡ୍",
            "privacy_badge_desc" to "ପଡ଼ୋଶୀ କୃଷକମାନଙ୍କ ସୁରକ୍ଷା ପାଇଁ ବେନାମୀ ସ୍କାନ୍ ଟେଲିମେଟ୍ରି ପ୍ରଦାନ କରାଯାଇଛି। କୌଣସି ବ୍ୟକ୍ତିଗତ ତଥ୍ୟ ଅଂଶୀଦାର କରାଯାଇ ନାହିଁ।"
        )
    )

    fun get(key: String, lang: String): String {
        return strings[lang]?.get(key) ?: strings["en"]?.get(key) ?: key
    }
}
