package com.example

object AppStrings {
    private val strings = mapOf(
        "en" to mapOf(
            "nav_home" to "Home",
            "market_rates" to "Live Mandi Rates",
            "nav_market" to "Market",
            "nav_scan" to "Scan",
            "nav_chat" to "Chat",
            "nav_profile" to "Profile",
            "detecting" to "Detecting...",
            "auto_detect" to "Auto-Detect Location",
            "powered_by" to "Direct Agmarknet Govt API Integration",
            "search_placeholder" to "Enter crop (e.g. Tomato, Wheat...)",
            "search_btn" to "Search",
            "popular_crops" to "Popular Crops",
            "fetching_live" to "Fetching live govt API data for",
            "no_live_data" to "No live market data found for",
            "try_different" to "Try a different crop or location.",
            "mandi" to "Mandi",
            "modal_price" to "Modal Price (INR/Quintal)",
            "variety" to "Variety:",
            "min" to "Min:",
            "max" to "Max:",
            "track_price" to "🔔 Track Price",
            "tracking_active" to "✅ Tracking",
            "edit_location" to "Edit Location",
            "enter_state" to "State (e.g. Punjab)",
            "enter_mandi" to "Mandi (e.g. Khanna)",
            "save" to "Save",
            "cancel" to "Cancel",
            "scanner_title" to "AI Crop Doctor",
            "take_photo" to "Take Photo",
            "upload_gallery" to "Upload Gallery",
            "analyzing" to "Analyzing image...",
            "chat_placeholder" to "Ask NuKropAI...",
            "chat_title" to "NuKropAI Assistant",
            "weather_alerts" to "Market & Weather Alerts Active",
            "nav_autopilot" to "Autopilot",
            "nav_finance" to "Finance",
            "nav_rental" to "Equipment",
            "nav_khata" to "Farm Khata",
            "good_farmer" to "Good %s, Farmer!",
            "quick_actions" to "Quick Actions",
            "scan_crop" to "Scan Crop",
            "ai_disease" to "AI Disease & Pest Detect",
            "scan_soil" to "Scan Soil",
            "ai_soil" to "AI Soil Health Analysis",
            "market_rates_action" to "Market Rates",
            "live_mandi_prices" to "Live Mandi Prices",
            "ai_advisor" to "AI Advisor",
            "ask_question" to "Ask Any Farm Question",
            "loan_subsidy" to "Loan & Subsidy",
            "govt_schemes" to "Govt Schemes Matcher",
            "field_navigator" to "Field Navigator",
            "gps_route" to "GPS Route & Coverage",
            "my_tracked" to "My Tracked Prices",
            "pest_radar" to "Hyperlocal Pest Prediction AI",
            "high_risk" to "HIGH RISK",
            "report_outbreak" to "Report Outbreak in My Field",
            "outbreak_logged" to "Outbreak logged. Neighboring farmers alerted!",
            "ai_tasks" to "AI Task Schedules",
            "farm_tips" to "Today's Farm Tips",
            "subsidy_title" to "Government Schemes AI",
            "ai_matcher" to "AI Scheme Matcher",
            "find_subsidies" to "FIND MY SUBSIDIES",
            "scanning_gov" to "Scanning Gov Databases..."
        ),
        "hi" to mapOf(
            "nav_home" to "होम",
            "market_rates" to "लाइव मंडी भाव",
            "nav_market" to "बाजार",
            "nav_scan" to "स्कैन",
            "nav_chat" to "चैट",
            "nav_profile" to "प्रोफ़ाइल",
            "detecting" to "पता लगा रहा है...",
            "auto_detect" to "स्थान स्वतः खोजें",
            "powered_by" to "प्रत्यक्ष एगमार्कनेट सरकारी एपीआई एकीकरण",
            "search_placeholder" to "फसल दर्ज करें (जैसे टमाटर, गेहूं...)",
            "search_btn" to "खोजें",
            "popular_crops" to "लोकप्रिय फसलें",
            "fetching_live" to "सरकारी एपीआई डेटा प्राप्त कर रहा है...",
            "no_live_data" to "इसके लिए कोई लाइव बाजार डेटा नहीं मिला:",
            "try_different" to "कोई अन्य फसल या स्थान आज़माएं।",
            "mandi" to "मंडी",
            "modal_price" to "औसत मूल्य (INR/क्विंटल)",
            "variety" to "किस्म:",
            "min" to "न्यूनतम:",
            "max" to "अधिकतम:",
            "track_price" to "🔔 मूल्य ट्रैक करें",
            "tracking_active" to "✅ ट्रैकिंग सक्रिय",
            "edit_location" to "स्थान बदलें",
            "enter_state" to "राज्य (जैसे पंजाब)",
            "enter_mandi" to "मंडी (जैसे खन्ना)",
            "save" to "सहेजें",
            "cancel" to "रद्द करें",
            "scanner_title" to "एआई फसल डॉक्टर",
            "take_photo" to "फोटो लें",
            "upload_gallery" to "गैलरी से अपलोड करें",
            "analyzing" to "छवि का विश्लेषण हो रहा है...",
            "chat_placeholder" to "NuKropAI से पूछें...",
            "chat_title" to "NuKropAI सहायक",
            "weather_alerts" to "बाजार और मौसम अलर्ट सक्रिय",
            "nav_autopilot" to "ऑटोपायलट",
            "nav_finance" to "वित्त",
            "good_farmer" to "शुभ %s, किसान!",
            "quick_actions" to "त्वरित कार्य",
            "scan_crop" to "फसल स्कैन",
            "ai_disease" to "एआई रोग एवं कीट पहचान",
            "scan_soil" to "मिट्टी स्कैन",
            "ai_soil" to "एआई मिट्टी स्वास्थ्य विश्लेषण",
            "market_rates_action" to "बाजार भाव",
            "live_mandi_prices" to "लाइव मंडी भाव",
            "ai_advisor" to "एआई सलाहकार",
            "ask_question" to "कोई भी कृषि प्रश्न पूछें",
            "loan_subsidy" to "ऋण एवं सब्सिडी",
            "govt_schemes" to "सरकारी योजना मैचर",
            "field_navigator" to "खेत नेविगेटर",
            "gps_route" to "GPS मार्ग एवं कवरेज",
            "my_tracked" to "मेरी ट्रैक की गई कीमतें",
            "pest_radar" to "हाइपरलोकल कीट पूर्वानुमान एआई",
            "high_risk" to "उच्च जोखिम",
            "report_outbreak" to "मेरे खेत में प्रकोप की रिपोर्ट करें",
            "outbreak_logged" to "प्रकोप दर्ज किया गया। पड़ोसी किसानों को सूचित किया!",
            "ai_tasks" to "एआई कार्य अनुसूची",
            "farm_tips" to "आज की कृषि सुझाव",
            "subsidy_title" to "सरकारी योजनाएं एआई",
            "ai_matcher" to "एआई योजना मैचर",
            "find_subsidies" to "मेरी सब्सिडी खोजें",
            "scanning_gov" to "सरकारी डेटाबेस स्कैन हो रहा है..."
        ),
        "te" to mapOf(
            "nav_home" to "హోమ్",
            "market_rates" to "ప్రత్యక్ష మార్కెట్ ధరలు",
            "nav_market" to "మార్కెట్",
            "nav_scan" to "స్కాన్",
            "nav_chat" to "చాట్",
            "nav_profile" to "ప్రొఫైల్",
            "detecting" to "కనుగొంటోంది...",
            "auto_detect" to "ఆటో-డిటెక్ట్ లొకేషన్",
            "powered_by" to "డైరెక్ట్ అగ్మార్కెట్ ప్రభుత్వ API ఇంటిగ్రేషన్",
            "search_placeholder" to "పంట పేరు నమోదు చేయండి (ఉదా. టమోటా, గోధుమ...)",
            "search_btn" to "వెతకండి",
            "popular_crops" to "ప్రముఖ పంటలు",
            "fetching_live" to "ప్రభుత్వ API డేటాను పొందుతోంది...",
            "no_live_data" to "దీనికి ప్రత్యక్ష మార్కెట్ డేటా కనుగొనబడలేదు:",
            "try_different" to "వేరే పంట లేదా స్థానాన్ని ప్రయత్నించండి.",
            "mandi" to "మండీ",
            "modal_price" to "సగటు ధర (INR/క్వింటాల్)",
            "variety" to "రకం:",
            "min" to "కనిష్ట:",
            "max" to "గరిష్ట:",
            "track_price" to "🔔 ధరను ట్రాక్ చేయండి",
            "tracking_active" to "✅ ట్రాకింగ్ అవుతోంది",
            "edit_location" to "స్థానాన్ని సవరించండి",
            "enter_state" to "రాష్ట్రం (ఉదా. పంజాబ్)",
            "enter_mandi" to "మండీ (ఉదా. ఖన్నా)",
            "save" to "సేవ్ చేయి",
            "cancel" to "రద్దు చేయి",
            "scanner_title" to "AI పంట డాక్టర్",
            "take_photo" to "ఫోటో తీయండి",
            "upload_gallery" to "గ్యాలరీ నుండి అప్‌లోడ్ చేయండి",
            "analyzing" to "చిత్రాన్ని విశ్లేషిస్తోంది...",
            "chat_placeholder" to "NuKropAI ని అడగండి...",
            "chat_title" to "NuKropAI సహాయకుడు",
            "weather_alerts" to "మార్కెట్ & వాతావరణ హెచ్చరికలు యాక్టివ్‌గా ఉన్నాయి",
            "nav_autopilot" to "ఆటోపైలట్",
            "nav_finance" to "ఫైనాన్స్",
            "subsidy_title" to "ప్రభుత్వ పథకాలు AI",
            "ai_matcher" to "AI స్కీమ్ మ్యాచర్",
            "find_subsidies" to "నా సబ్సిడీలను కనుగొనండి",
            "scanning_gov" to "ప్రభుత్వ డేటాబేస్లను స్కాన్ చేస్తోంది..."
        ),
        "ta" to mapOf(
            "nav_home" to "முகப்பு",
            "market_rates" to "நேரடி மண்டி விலைகள்",
            "nav_market" to "சந்தை",
            "nav_scan" to "ஸ்கேன்",
            "nav_chat" to "அரட்டை",
            "nav_profile" to "சுயவிவரம்",
            "detecting" to "கண்டறியப்படுகிறது...",
            "auto_detect" to "தானாக கண்டறியும் இடம்",
            "powered_by" to "நேரடி அக்மார்க்நெட் அரசு ஏபிஐ ஒருங்கிணைப்பு",
            "search_placeholder" to "பயிரை உள்ளிடவும் (எ.கா. தக்காளி, கோதுமை...)",
            "search_btn" to "தேடு",
            "popular_crops" to "பிரபலமான பயிர்கள்",
            "fetching_live" to "நேரடி அரசு ஏபிஐ தரவு பெறப்படுகிறது...",
            "no_live_data" to "இதற்கான நேரடி சந்தை தரவு எதுவும் கிடைக்கவில்லை:",
            "try_different" to "வேறு பயிர் அல்லது இடத்தை முயற்சிக்கவும்.",
            "mandi" to "மண்டி",
            "modal_price" to "சராசரி விலை (INR/குவிண்டால்)",
            "variety" to "வகை:",
            "min" to "குறைந்தபட்ச:",
            "max" to "அதிகபட்ச:",
            "track_price" to "🔔 விலையை கண்காணிக்கவும்",
            "tracking_active" to "✅ கண்காணிப்பில் உள்ளது",
            "edit_location" to "இடத்தைத் திருத்தவும்",
            "enter_state" to "மாநிலம் (எ.கா. பஞ்சாப்)",
            "enter_mandi" to "மண்டி (எ.கா. கண்ணா)",
            "save" to "சேமி",
            "cancel" to "ரத்துசெய்",
            "scanner_title" to "AI பயிர் மருத்துவர்",
            "take_photo" to "புகைப்படம் எடு",
            "upload_gallery" to "கேலரியில் இருந்து பதிவேற்றவும்",
            "analyzing" to "படம் பகுப்பாய்வு செய்யப்படுகிறது...",
            "chat_placeholder" to "NuKropAI இடம் கேளுங்கள்...",
            "chat_title" to "NuKropAI உதவியாளர்",
            "weather_alerts" to "சந்தை மற்றும் வானிலை எச்சரிக்கைகள் செயலில் உள்ளன",
            "nav_autopilot" to "ஆட்டோபைலட்",
            "nav_finance" to "நிதி",
            "subsidy_title" to "அரசு திட்டங்கள் AI",
            "ai_matcher" to "AI திட்ட மேட்சர்",
            "find_subsidies" to "எனது மானியங்களைக் கண்டறியுங்கள்",
            "scanning_gov" to "அரசு தரவுத்தளங்களை ஸ்கேன் செய்கிறது..."
        ),
        "mr" to mapOf(
            "nav_home" to "होम",
            "market_rates" to "थेट बाजार भाव",
            "nav_market" to "बाजार",
            "nav_scan" to "स्कॅन",
            "nav_chat" to "चॅट",
            "nav_profile" to "प्रोफाइल",
            "detecting" to "शोधत आहे...",
            "auto_detect" to "स्थान स्वयंचलित शोधा",
            "powered_by" to "थेट एगमार्कनेट सरकारी एपीआय एकत्रीकरण",
            "search_placeholder" to "पीक प्रविष्ट करा (उदा. टोमॅटो, गहू...)",
            "search_btn" to "शोधा",
            "popular_crops" to "लोकप्रिय पिके",
            "fetching_live" to "थेट सरकारी एपीआय डेटा मिळवत आहे...",
            "no_live_data" to "यासाठी थेट बाजार डेटा आढळला नाही:",
            "try_different" to "वेगळे पीक किंवा स्थान वापरून पहा.",
            "mandi" to "मंडी",
            "modal_price" to "सरासरी किंमत (INR/क्विंटल)",
            "variety" to "जात:",
            "min" to "किमान:",
            "max" to "कमाल:",
            "track_price" to "🔔 किंमत ट्रॅक करा",
            "tracking_active" to "✅ ट्रॅकिंग सक्रिय",
            "edit_location" to "स्थान बदला",
            "enter_state" to "राज्य (उदा. पंजाब)",
            "enter_mandi" to "मंडी (उदा. खन्ना)",
            "save" to "जतन करा",
            "cancel" to "रद्द करा",
            "scanner_title" to "एआई पीक डॉक्टर",
            "take_photo" to "फोटो काढा",
            "upload_gallery" to "गॅलरीमधून अपलोड करा",
            "analyzing" to "प्रतिमेचे विश्लेषण करत आहे...",
            "chat_placeholder" to "NuKropAI ला विचारा...",
            "chat_title" to "NuKropAI सहाय्यक",
            "weather_alerts" to "बाजार आणि हवामान सूचना सक्रिय",
            "nav_autopilot" to "ऑटोपायलट",
            "nav_finance" to "वित्त",
            "subsidy_title" to "सरकारी योजना AI",
            "ai_matcher" to "AI योजना मॅचर",
            "find_subsidies" to "माझे अनुदान शोधा",
            "scanning_gov" to "सरकारी डेटाबेस स्कॅन होत आहे..."
        )
    )

    fun get(key: String, lang: String): String {
        return strings[lang]?.get(key) ?: strings["en"]?.get(key) ?: key
    }
}
